---

- name: first container with flask
  docker_container:
    name: flaskapp_1
    hostname: flaskapp_1
    image: "{{ dockerhub_app }}"
    exposed_ports: "5000"
    ports: "5001:5000"
    state: started
    networks: 
      - name: snet

- name: second container with flask
  docker_container:
    name: flaskapp_2
    hostname: flaskapp_2
    image: "{{ dockerhub_app }}"
    ports: "5002:5000"
    state: started
    networks:
      - name: snet

- name: third container with flask
  docker_container:
    name: flaskapp_3
    hostname: flaskapp_3
    image: "{{ dockerhub_app }}"
    ports: "5003:5000"
    state: started
    networks:
      - name: snet
