---

- name: log into private registry and force re-authorization
  docker_login:
    registry: "deusdimitrius/epam_exam:flaskapp"
    username: "deusdimitrius"
    password: "{{ dockerhub_password }}"
    reauthorize: yes

- name: pull image from Dockerhub
  docker_image:
  name: "deusdimitrius/epam_exam:flaskapp"

- name: create docker network
  shell: docker network create dnet

#- name: create a network
#  docker_network:
#    name: network

- name: add container to networks
  docker_container:
    name: "{{ dockerhub_app }}"
    exposed_ports:
      - 5000
    networks:
      - name: docker-net
        links: flaskapp

