---

#- name: create docker network
#  become: true
#  become_method: sudo
#  docker_network:
#    name: docker_network
#    state: present

- name: login to DockerHub
  docker_hub_login:
    username: "{{ dockerhub_name }}"
    password: "{{ dockerhub_password }}"

- name: pull image from Dockerhub
  docker_hub_image:
  name: "{{ dockerhub_app }}"

#- name: Add container to networks
#  docker_container:
#    name: "{{ dockerhub_app }}"
#    ports: 5000:5000
#    networks:
#      - name: docker_network
#        links: flaskapp

