---

- name: log into private registry and force re-authorization
  docker_login:
    registry: "{{ dockerhub_app }}"
    username: "{{ dockerhub_name }}"
    password: "{{ dockerhub_password }}"
    reauthorize: yes

- name: pull image from Dockerhub
  docker_image:
  name: "{{ dockerhub_app }}"

#- name: create docker network
#  shell: docker network create dnet
#
#- name add container to network
#  shell: docker run -d -p 5000:5000 --network=dnet  --name=flask {{ dockerhub_app }}

- name: create a network
  docker_network:
    name: dnet
    state: present

- name: add container 
  docker_container:
    name: flaskapp
    state: started
    image: "{{ dockerhub_app }}"
    ports: "5000:5000"
    networks:
      - name: dnet
        links: flaskapp

#- name: Add all containers to network
#  docker_network:
#    name: dnet
#    state: present
#    connected:
#      - container_a
#      - container_b
#      - container_c
#    appends: yes
